#!/usr/bin/env python3
"""Regenerate data/newbuilds.js from the london-newbuilds research catalog.

Fetches the research catalog and the promotion-gap register from a pinned
commit of https://github.com/jkee/london-newbuilds (an immutable SHA, so the
build stays reproducible), filters to the map's scope, and writes
data/newbuilds.js.

What is kept (all quality-gate reviewed, with coordinates, inside the
interest-zone ring from data/zone.js):
  - all "B — investigate" records, each carrying its open due-diligence
    gates ("verify before committing" tags) and known-issues note;
  - "C — hold" records whose hold_verdict is probably-ok (mostly future,
    not-yet-delivered schemes) or probably-bad (operational failures and
    confirmed safety defects — shown demoted with a specific warning);
  - dropped: not-applicable C holds (product-fit/ordinary/context noise for
    a premium-flat hunt) and the unreviewed discovery pipeline.

Tags name the thing to check, not a verdict, and safety/operations notes are
time-stamped (asof) — both per the research project's own framing rules.

Usage:
  python3 scripts/build-newbuilds.py
"""

import csv
import hashlib
import io
import json
import re
import sys
import urllib.request
from pathlib import Path

REPO = "jkee/london-newbuilds"
# "Triage the reviewed C hold lane into buckets and verdicts" — the first
# commit carrying hold_bucket/hold_verdict, primary_url and the refreshed
# promotion-gap register together.
REF = "5c0da2a2aad2595a594d88afe251e4c4e53bcde7"
RAW_BASE = f"https://raw.githubusercontent.com/{REPO}/{REF}"
CATALOG = f"{RAW_BASE}/data/catalog/developments.csv"
GAP_REGISTER = f"{RAW_BASE}/outputs/promotion-gap-register.csv"

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "data" / "newbuilds.js"
ZONE_PATH = ROOT / "data" / "zone.js"


def fetch_csv(url: str) -> list[dict]:
    with urllib.request.urlopen(url) as resp:
        return list(csv.DictReader(io.StringIO(resp.read().decode("utf-8"))))


def load_zone_ring() -> list[tuple[float, float]]:
    text = ZONE_PATH.read_text()
    ring = [
        (float(lat), float(lng))
        for lat, lng in re.findall(r"\[\s*(5\d\.\d+),\s*(-?\d\.\d+)\s*\]", text)
    ]
    if len(ring) < 3:
        sys.exit(f"could not parse zone ring from {ZONE_PATH}")
    return ring


def inside(ring: list[tuple[float, float]], lat: float, lng: float) -> bool:
    result = False
    j = len(ring) - 1
    for i in range(len(ring)):
        la1, lo1 = ring[i]
        la2, lo2 = ring[j]
        if (lo1 > lng) != (lo2 > lng) and lat < (la2 - la1) * (lng - lo1) / (lo2 - lo1) + la1:
            result = not result
        j = i
    return result


def main() -> None:
    rows = fetch_csv(CATALOG)
    gates = {
        row["development_id"]: [g for g in row["open_gates"].split("|") if g]
        for row in fetch_csv(GAP_REGISTER)
    }
    ring = load_zone_ring()

    kept = []
    for row in rows:
        if row["review_status"] != "quality-gate":
            continue
        lane = row["classification"]
        verdict = row["hold_verdict"]
        if lane == "C" and verdict not in ("probably-ok", "probably-bad"):
            continue
        if not row["latitude"] or not row["longitude"]:
            continue
        lat, lng = float(row["latitude"]), float(row["longitude"])
        if not inside(ring, lat, lng):
            continue
        rec = {
            "id": row["development_id"],
            "name": row["canonical_name"],
            "lane": lane,
            "lat": round(lat, 5),
            "lng": round(lng, 5),
            "year": row["effective_year"].strip(),
            "type": row["development_type"].strip(),
            "developer": row["developer"].strip(),
            "homes": row["homes"].strip(),
            "postcode": re.split(r"[|;,]", row["postcodes"])[0].strip(),
            "url": row["primary_url"].strip(),
            "note": row["known_issues"].strip(),
            "asof": row["last_reviewed"].strip(),
        }
        if lane == "B":
            rec["verify"] = gates.get(rec["id"], [])
        else:
            rec["verdict"] = verdict.removeprefix("probably-")
            rec["bucket"] = row["hold_bucket"]
        kept.append(rec)
    kept.sort(key=lambda r: r["name"].lower())

    counts = {
        "B": sum(1 for r in kept if r["lane"] == "B"),
        "C ok": sum(1 for r in kept if r.get("verdict") == "ok"),
        "C bad": sum(1 for r in kept if r.get("verdict") == "bad"),
    }

    def js(row: dict) -> str:
        fields = ", ".join(
            f"{key}: {json.dumps(value, ensure_ascii=False)}" for key, value in row.items()
        )
        return f"  {{ {fields} }},"

    header = f"""\
// New-build / major-conversion developments — reviewed records from the
// london-newbuilds research project (https://github.com/{REPO}).
//
// GENERATED by scripts/build-newbuilds.py — do not edit by hand.
// Source: data/catalog/developments.csv + outputs/promotion-gap-register.csv
// at pinned commit {REF[:7]}.
// Kept: quality-gate reviewed, inside the data/zone.js interest ring —
// {counts["B"]} B-investigate, {counts["C ok"]} C probably-ok holds (mostly future schemes),
// {counts["C bad"]} C probably-bad holds (shown demoted, with specific warnings).
// Dropped: not-applicable C holds and the unreviewed discovery pipeline.
//
// lane "B": verify = open due-diligence gates (check before committing),
//   note = known-issues text from the catalog, asof = last review date.
// lane "C": verdict = "ok" | "bad", bucket = hold reason
//   (not-yet-delivered / safety-unresolved / identity-evidence-gap /
//   operational-failure / safety-defect-confirmed), note + asof as above.
// The full claim-level evidence trail lives in the research repo — look up
// the id there.

window.NEWBUILDS = [
"""
    OUT_PATH.write_text(header + "\n".join(js(row) for row in kept) + "\n];\n")
    print(f"wrote {OUT_PATH} — {len(kept)} records ({counts})")


if __name__ == "__main__":
    main()
