#!/usr/bin/env python3
"""Regenerate data/newbuilds.js from the london-newbuilds research release.

Fetches the frozen, checksummed catalog from the pinned release tag of
https://github.com/jkee/london-newbuilds, verifies it against the release
manifest, filters it down to the map's scope, and writes data/newbuilds.js.

Filter (the public default):
  - review_status == "quality-gate"  (drops the unreviewed discovery pipeline)
  - classification == "B"            (reviewed "investigate" lane; --lanes B,C
                                      adds the reviewed holds for local use)
  - has coordinates, inside the interest-zone ring from data/zone.js

Only neutral facts are emitted (name, coords, year, type, developer, homes,
postcode, catalog id). The research project's judgment prose, safety columns
and evidence trail stay upstream — follow the id there for the full record.

Usage:
  python3 scripts/build-newbuilds.py [--lanes B,C]
"""

import argparse
import csv
import hashlib
import io
import json
import re
import sys
import urllib.request
from pathlib import Path

REPO = "jkee/london-newbuilds"
TAG = "zone-1-2-v1"
CATALOG_FILE = "zone-1-2-catalog-v1.csv"
RAW_BASE = f"https://raw.githubusercontent.com/{REPO}/{TAG}/outputs"

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "data" / "newbuilds.js"
ZONE_PATH = ROOT / "data" / "zone.js"


def fetch(url: str) -> bytes:
    with urllib.request.urlopen(url) as resp:
        return resp.read()


def load_zone_ring() -> list[tuple[float, float]]:
    text = ZONE_PATH.read_text()
    ring = [
        (float(lat), float(lng))
        for lat, lng in re.findall(r"\[\s*(5\d\.\d+),\s*(-?\d\.\d+)\s*\]", text)
    ]
    if len(ring) < 3:
        sys.exit(f"could not parse zone ring from {ZONE_PATH}")
    return ring


def inside(ring: list[tuple[float, float]], lat: float, lng: float) -> bool:
    result = False
    j = len(ring) - 1
    for i in range(len(ring)):
        la1, lo1 = ring[i]
        la2, lo2 = ring[j]
        if (lo1 > lng) != (lo2 > lng) and lat < (la2 - la1) * (lng - lo1) / (lo2 - lo1) + la1:
            result = not result
        j = i
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lanes", default="B",
                        help="comma-separated classifications to keep (default: B)")
    lanes = {lane.strip().upper() for lane in parser.parse_args().lanes.split(",")}

    manifest = json.loads(fetch(f"{RAW_BASE}/v1-manifest.json"))
    raw = fetch(f"{RAW_BASE}/{CATALOG_FILE}")
    expected = manifest["files"][CATALOG_FILE]["sha256"]
    actual = hashlib.sha256(raw).hexdigest()
    if actual != expected:
        sys.exit(f"checksum mismatch for {CATALOG_FILE}: expected {expected}, got {actual}")

    ring = load_zone_ring()
    rows = list(csv.DictReader(io.StringIO(raw.decode("utf-8"))))

    kept = []
    for row in rows:
        if row["review_status"] != "quality-gate":
            continue
        if row["classification"] not in lanes:
            continue
        if not row["latitude"] or not row["longitude"]:
            continue
        lat, lng = float(row["latitude"]), float(row["longitude"])
        if not inside(ring, lat, lng):
            continue
        kept.append({
            "id": row["development_id"],
            "name": row["canonical_name"],
            "lane": row["classification"],
            "lat": round(lat, 5),
            "lng": round(lng, 5),
            "year": row["effective_year"].strip(),
            "type": row["development_type"].strip(),
            "developer": row["developer"].strip(),
            "homes": row["homes"].strip(),
            "postcode": re.split(r"[|;,]", row["postcodes"])[0].strip(),
        })
    kept.sort(key=lambda r: r["name"].lower())

    def js(row: dict) -> str:
        fields = ", ".join(
            f"{key}: {json.dumps(value, ensure_ascii=False)}" for key, value in row.items()
        )
        return f"  {{ {fields} }},"

    header = f"""\
// New-build / major-conversion developments — reviewed candidates from the
// london-newbuilds research project (https://github.com/{REPO}).
//
// GENERATED by scripts/build-newbuilds.py — do not edit by hand.
// Source: release {TAG} ({manifest["release_id"]}), outputs/{CATALOG_FILE},
// verified against v1-manifest.json (sha256).
// Filter: quality-gate reviewed, lane(s) {"+".join(sorted(lanes))}, inside the
// data/zone.js interest ring. {len(kept)} of {len(rows)} catalog records kept.
// Fields are neutral facts only; classification reasons, safety notes and the
// claim-level evidence trail live in the research repo — look up the id there.
// lane: "B" = reviewed, worth investigating; "C" = reviewed hold/exclusion.

window.NEWBUILDS = [
"""
    OUT_PATH.write_text(header + "\n".join(js(row) for row in kept) + "\n];\n")
    print(f"wrote {OUT_PATH} — {len(kept)} records (lanes: {', '.join(sorted(lanes))})")


if __name__ == "__main__":
    main()
